import { Bundle } from '@/components/BundleCard';
import { Course } from '@/components/CourseCard';

export const DEMO_BUNDLES: Bundle[] = [
  {
    id: '1',
    title: 'Full Stack Developer Bundle',
    description: 'Complete path from frontend to backend development',
    courses: 5,
    originalPrice: 500,
    discountedPrice: 300,
    discount: 40,
  },
  {
    id: '2',
    title: 'Data Science Master Bundle',
    description: 'Everything you need to become a data scientist',
    courses: 6,
    originalPrice: 600,
    discountedPrice: 360,
    discount: 40,
  },
  {
    id: '3',
    title: 'Mobile Development Bundle',
    description: 'Build iOS and Android apps from scratch',
    courses: 4,
    originalPrice: 400,
    discountedPrice: 260,
    discount: 35,
  },
  {
    id: '4',
    title: 'UI/UX Design Complete Bundle',
    description: 'Master design thinking and user experience',
    courses: 7,
    originalPrice: 550,
    discountedPrice: 330,
    discount: 40,
  },
  {
    id: '5',
    title: 'DevOps Engineer Bundle',
    description: 'Learn CI/CD, Docker, Kubernetes and cloud platforms',
    courses: 5,
    originalPrice: 480,
    discountedPrice: 312,
    discount: 35,
  },
  {
    id: '6',
    title: 'Machine Learning Practitioner Bundle',
    description: 'Practical ML projects and MLOps basics',
    courses: 5,
    originalPrice: 650,
    discountedPrice: 390,
    discount: 40,
  },
  {
    id: '7',
    title: 'Cloud Architect Bundle',
    description: 'AWS/GCP fundamentals and architecture patterns',
    courses: 6,
    originalPrice: 700,
    discountedPrice: 455,
    discount: 35,
  },
  {
    id: '8',
    title: 'Frontend Mastery Bundle',
    description: 'Advanced HTML/CSS/JS and modern frameworks',
    courses: 6,
    originalPrice: 520,
    discountedPrice: 312,
    discount: 40,
  },
];

export const DEMO_COURSES: Course[] = [
  {
    id: '1',
    title: 'Advanced React Patterns',
    description: 'Master advanced React patterns including render props, HOCs, and custom hooks',
    instructor: 'Sarah Johnson',
    duration: '8 weeks',
    students: 245,
    price: 99,
    category: 'Web Development',
  },
  {
    id: '2',
    title: 'TypeScript Fundamentals',
    description: 'Learn TypeScript from basics to advanced type systems',
    instructor: 'Mike Chen',
    duration: '6 weeks',
    students: 389,
    price: 79,
    category: 'Programming',
  },
  {
    id: '3',
    title: 'Node.js Backend Development',
    description: 'Build scalable backend applications with Node.js and Express',
    instructor: 'Alex Rodriguez',
    duration: '10 weeks',
    students: 167,
    price: 119,
    category: 'Backend',
  },
  {
    id: '4',
    title: 'UI/UX Design Principles',
    description: 'Design beautiful and intuitive user interfaces',
    instructor: 'Emma Watson',
    duration: '5 weeks',
    students: 512,
    price: 89,
    category: 'Design',
  },
  {
    id: '5',
    title: 'Python for Data Science',
    description: 'Analyze data and build ML models with Python',
    instructor: 'David Lee',
    duration: '12 weeks',
    students: 678,
    price: 149,
    category: 'Data Science',
  },
  {
    id: '6',
    title: 'Mobile App Development with React Native',
    description: 'Build cross-platform mobile apps',
    instructor: 'Lisa Park',
    duration: '9 weeks',
    students: 234,
    price: 129,
    category: 'Mobile',
  },
  {
    id: '7',
    title: 'Intro to SQL and Databases',
    description: 'Relational databases, queries and performance basics',
    instructor: 'Robert King',
    duration: '4 weeks',
    students: 412,
    price: 59,
    category: 'Data',
  },
  {
    id: '8',
    title: 'Kubernetes for Developers',
    description: 'Deploy and manage containerized applications at scale',
    instructor: 'Nina Patel',
    duration: '6 weeks',
    students: 198,
    price: 129,
    category: 'DevOps',
  },
  {
    id: '9',
    title: 'GraphQL APIs',
    description: 'Design and implement GraphQL servers and clients',
    instructor: 'Ethan Brooks',
    duration: '5 weeks',
    students: 150,
    price: 89,
    category: 'Backend',
  },
  {
    id: '10',
    title: 'Design Systems with Figma',
    description: 'Create and maintain scalable design systems',
    instructor: 'Olivia Gomez',
    duration: '3 weeks',
    students: 320,
    price: 49,
    category: 'Design',
  },
];

export default {
  DEMO_BUNDLES,
  DEMO_COURSES,
};
